[package]
name = "web_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rocket_contrib = "0.4.11"
serde_json = "1.0.128"
uuid = "1.10.0"



[dependencies.rocket]
version = "0.5.1"
features = [ "json" ]

[dependencies.serde]
version = "1.0.210"
features = [ "derive" ]
